piVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: kustomize
    repoURL: 'https://github.com/fc277073030/argocd-demo.git'
    targetRevision: HEAD
    kustomize:
      images:
        -  gcr.io/heptio-images/ks-guestbook-demo:0.2
  project: default
  syncPolicy:
    automated:
      automated:
        prune: false
        selfHeal: false